#!/bin/bash
# Copyright (C) Metaswitch Networks 2016
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

rm -rf autogenerated_rst_docs/*.rst autogenerated_rst_docs/img autogenerated_rst_docs/sample_files

for filename in docs/*.md
do
  # Change docs/xyz.md to just xyz.md
  filename_base=$(basename "$filename")
  # Change xyz.md to just xyz
  filename_without_suffix=${filename_base%.*}
  target="autogenerated_rst_docs/${filename_without_suffix}.rst"
  pandoc --from markdown --to rst $filename -o $target
  # Change all the internal references to .md files so they refer to the generated .html files
  # Use a restricted regex match so we don't accidentally convert external links like https://github.com/Metaswitch/sprout/blob/master/docs/Development.md to https://github.com/Metaswitch/sprout/blob/master/docs/Development.html
  sed -ri "s/<([\.0-9a-zA-Z_]+?)\.md/<\1.html/g" $target
done

cp -a docs/img autogenerated_rst_docs/img
cp -a docs/sample_files autogenerated_rst_docs/sample_files

# At this point index.rst contains the text generated from index.md, so we want
# to append the table of contents to the end of that
python yaml_to_toctree.py >> autogenerated_rst_docs/index.rst
