#!/bin/bash
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2016  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.

rm -rf autogenerated_rst_docs/*.rst autogenerated_rst_docs/img autogenerated_rst_docs/sample_files

for filename in docs/*.md
do
  # Change docs/xyz.md to just xyz.md
  filename_base=$(basename "$filename")
  # Change xyz.md to just xyz
  filename_without_suffix=${filename_base%.*}
  target="autogenerated_rst_docs/${filename_without_suffix}.rst"
  pandoc --from markdown --to rst $filename -o $target
  # Change all the internal references to .md files so they refer to the generated .html files
  # Use a restricted regex match so we don't accidentally convert external links like https://github.com/Metaswitch/sprout/blob/master/docs/Development.md to https://github.com/Metaswitch/sprout/blob/master/docs/Development.html
  sed -ri "s/<([a-zA-Z_]+?)\.md/<\1.html/g" $target
done

cp -a docs/img autogenerated_rst_docs/img
cp -a docs/sample_files autogenerated_rst_docs/sample_files

# At this point index.rst contains the text generated from index.md, so we want
# to append the table of contents to the end of that
python yaml_to_toctree.py >> autogenerated_rst_docs/index.rst
