site_name: Clearwater Docs Home
pages:
# Overview:
- ['index.md', 'Home']
- ['Clearwater_Architecture.md', 'Clearwater Architecture']
- ['Clearwater_Tour.md', 'Clearwater Tour']
- ['Exploring_Clearwater.md', 'Exploring Clearwater']
- ['Support.md', 'Support']
- ['Troubleshooting_and_Recovery.md', 'Troubleshooting and Recovery']

# Installation:
- ['Installation_Instructions.md', 'Installation', 'Installation Instructions']
- ['All_in_one_Images.md', 'Installation', 'All-in-one Images']
- ['Automated_Install.md', 'Installation', 'Automated Install']
- ['Manual_Install.md', 'Installation', 'Manual Install']
- ['All_in_one_EC2_AMI_Installation.md', 'Installation', 'All in one EC2 AMI Installation']
- ['All_in_one_OVF_Installation.md', 'Installation', 'All-in-one OVF Installation']
- ['Installing_a_Chef_server.md', 'Installation', 'Installing a Chef server']
- ['Installing_a_Chef_workstation.md', 'Installation', 'Installing a Chef workstation']
- ['Creating_a_deployment_environment.md', 'Installation', 'Creating a deployment environment']
- ['Creating_a_deployment_with_Chef.md', 'Installation', 'Creating a deployment with Chef']
- ['Making_your_first_call.md', 'Installation', 'Making your first call']
- ['Configuring_the_native_Android_SIP_client.md', 'Installation', 'Configuring the native Android SIP client']
- ['Configuring_Zoiper_Android_iOS_Client.md', 'Installation', 'Configuring Zoiper Android/iOS Client']

# Upgrading and Modifying
- ['Upgrading_a_Clearwater_deployment.md', 'Upgrading and Modifying', 'Upgrading a Clearwater deployment']
- ['Modifying_Clearwater_settings.md', 'Upgrading and Modifying', 'Modifying Clearwater settings']
- ['Clearwater_Configuration_Options_Reference.md', 'Upgrading and Modifying', 'Clearwater Configuration Options Reference']
- ['Migrating_To_etcd.md', 'Upgrading and Modifying', 'Migrating to Automatic Clustering and Config Sharing']

# Integration:
- ['Configuring_an_Application_Server.md', 'Integration', 'Configuring an Application Server']
- ['External_HSS_Integration.md', 'Integration', 'External HSS Integration']
- ['OpenIMSCore_HSS_Integration.md', 'Integration', 'OpenIMSCore HSS Integration']
- ['CDF_Integration.md', 'Integration', 'CDF Integration']
- ['Clearwater_IP_Port_Usage.md', 'Integration', 'Clearwater Firewall Configuration']
- ['Clearwater_DNS_Usage.md', 'Integration', 'Clearwater DNS Usage']
- ['ENUM.md', 'Integration', 'ENUM']
- ['Voxbone.md', 'Integration', 'Voxbone']
- ['Clearwater_SNMP_Statistics.md', 'Integration', 'Clearwater SNMP Statistics']
- ['SNMP_Alarms.md', 'Integration', 'SNMP Alarms']
- ['Radius_Authentication.md', 'Integration', 'Radius Login Authentication']

# Features:
- ['Application_Server_Guide.md', 'Features', 'Application Server Guide']
- ['WebRTC_support_in_Clearwater.md', 'Features', 'WebRTC support in Clearwater']
- ['IR.92_Supplementary_Services.md', 'Features', 'IR.92 Supplementary Services']
- ['Backups.md', 'Features', 'Backups']
- ['Clearwater_Call_Barring_Support.md', 'Features', 'Clearwater Call Barring Support']
- ['Clearwater_Call_Diversion_Support.md', 'Features', 'Clearwater Call Diversion Support']
- ['Clearwater_Elastic_Scaling.md', 'Features', 'Clearwater Elastic Scaling']
- ['Clearwater_Privacy_Feature.md', 'Features', 'Clearwater Privacy Feature']
- ['IBCF.md', 'Features', 'IBCF']
- ['Multiple_Domains.md', 'Features', 'Multiple Domains']
- ['Multiple_Network_Support.md', 'Features', 'Multiple Network Support']
- ['Geographic_redundancy.md', 'Features', 'Geographic redundancy']
- ['IPv6.md', 'Features', 'IPv6']
- ['SIP_Interface_Specifications.md', 'Features', 'SIP Interface Specifications']
- ['Automatic_Clustering_Config_Sharing.md', 'Features', 'Automatic Clustering and Configuration Sharing']
- ['Provisioning_Subscribers.md', 'Features', 'Provisioning Subscribers']

# Failure Recovery:
- ['Handling_Failed_Nodes.md', 'Failure Recovery', 'Permanent Node Failures']

# Development:
- ['Clearwater_CPP_Coding_Guidelines.md', 'Development', 'Clearwater C++ Coding Guidelines']
- ['Clearwater_Ruby_Coding_Guidelines.md', 'Development', 'Clearwater Ruby Coding Guidelines']
- ['Debugging_Bono_Sprout_and_Homestead_with_GDB_and_Valgrind.md', 'Development', 'Debugging Bono, Sprout and Homestead with GDB and Valgrind']
- ['Pull_request_process.md', 'Development', 'Pull request process']

# Testing:
- ['Clearwater_stress_testing.md', 'Testing', 'Clearwater stress testing']
- ['Cacti.md', 'Testing', 'Cacti']
- ['Running_the_live_tests.md', 'Testing', 'Running the live tests']

theme: readthedocs
use_directory_urls: false
markdown_extensions: [sane_lists, admonition]
