site_name: Clearwater
pages:
# Overview:
- ['index.md', 'Home']
- ['Clearwater Architecture.md', 'Clearwater Architecture']
- ['Clearwater Tour.md', 'Clearwater Tour']
- ['Exploring Clearwater.md', 'Exploring Clearwater']
- ['Support.md', 'Support']
- ['Troubleshooting-and-Recovery.md', 'Troubleshooting and Recovery']

# Installation:
- ['Installation Instructions.md', 'Installation', 'Installation Instructions']
- ['All in one Images.md', 'Installation', 'All in one Images']
- ['Automated Install.md', 'Installation', 'Automated Install']
- ['Manual Install.md', 'Installation', 'Manual Install']
- ['Making your first call.md', 'Installation', 'Making your first call']
- ['All in one EC2 AMI Installation.md', 'Installation', 'All in one EC2 AMI Installation']
- ['All-in-one OVF Installation.md', 'Installation', 'All-in-one OVF Installation']
- ['Installing a Chef client.md', 'Installation', 'Installing a Chef client']
- ['Installing a Chef server.md', 'Installation', 'Installing a Chef server']
- ['Creating a deployment environment.md', 'Installation', 'Creating a deployment environment']
- ['Creating a deployment with Chef.md', 'Installation', 'Creating a deployment with Chef']
- ['Modifying-Clearwater-settings.md', 'Installation', 'Modifying Clearwater settings']
- ['Clearwater Configuration Options Reference.md', 'Installation', 'Clearwater Configuration Options Reference']
- ['Configuring the native Android SIP client.md', 'Installation', 'Configuring the native Android SIP client']
- ['Configuring-Zoiper-Android-iOS-Client.md', 'Installation', 'Configuring Zoiper Android/iOS Client']

# Integration:
- ['Configuring an Application Server.md', 'Integration', 'Configuring an Application Server']
- ['External HSS Integration.md', 'Integration', 'External HSS Integration']
- ['OpenIMSCore HSS Integration.md', 'Integration', 'OpenIMSCore HSS Integration']
- ['CDF Integration.md', 'Integration', 'CDF Integration']
- ['Clearwater-IP-Port-Usage.md', 'Integration', 'Clearwater Firewall Configuration']
- ['Clearwater-DNS-Usage.md', 'Integration', 'Clearwater DNS Usage']
- ['ENUM.md', 'Integration', 'ENUM']
- ['Plivo.md', 'Integration', 'Plivo']
- ['Voxbone.md', 'Integration', 'Voxbone']
- ['Clearwater-SNMP-Statistics.md', 'Integration', 'Clearwater SNMP Statistics']
- ['Configuring-M-Monit.md', 'Integration', 'Configuring M/Monit']

# Features:
- ['Application Server Guide.md', 'Features', 'Application Server Guide']
- ['WebRTC support in Clearwater.md', 'Features', 'WebRTC support in Clearwater']
- ['IR.92-Supplementary-Services.md', 'Features', 'IR.92 Supplementary Services']
- ['Backups.md', 'Features', 'Backups']
- ['Clearwater Call Barring Support.md', 'Features', 'Clearwater Call Barring Support']
- ['Clearwater Call Diversion Support.md', 'Features', 'Clearwater Call Diversion Support']
- ['Clearwater-Elastic-Scaling.md', 'Features', 'Clearwater Elastic Scaling']
- ['Clearwater Privacy Feature.md', 'Features', 'Clearwater Privacy Feature']
- ['IBCF.md', 'Features', 'IBCF']
- ['Multiple-Domains.md', 'Features', 'Multiple Domains']
- ['Multiple-Network-Support.md', 'Features', 'Multiple Network Support']
- ['Geographic redundancy.md', 'Features', 'Geographic redundancy']
- ['IPv6.md', 'Features', 'IPv6']
- ['SIP Interface Specifications.md', 'Features', 'SIP Interface Specifications']

# Development:
- ['Clearwater-CPP-Coding-Guidelines.md', 'Development', 'Clearwater C++ Coding Guidelines']
- ['Clearwater-Ruby-Coding-Guidelines.md', 'Development', 'Clearwater Ruby Coding Guidelines']
- ['Debugging-Bono,-Sprout-and-Homestead-with-GDB-and-Valgrind.md', 'Development', 'Debugging Bono, Sprout and Homestead with GDB and Valgrind']
- ['Pull-request-process.md', 'Development', 'Pull request process']

# Testing:
- ['Clearwater-stress-testing.md', 'Testing', 'Clearwater stress testing']
- ['Cacti.md', 'Testing', 'Cacti']
- ['Running the live tests.md', 'Testing', 'Running the live tests']

theme: readthedocs
include_search: true
use_directory_urls: false
markdown_extensions: [sane_lists, wikilinks, admonition]
